### ISSUE TITLE
blanket

### ISSUE THREAD

**Issue by alu0100622492** [noe-jacoboDSI/mocha_chai_definitivo#4]
https://github.com/alex-seville/blanket/blob/master/docs/getting_started_browser.md

con respecto a lo del blanket en este link esta clarito y parece que no es mas que descargarlo y añadir en los script del html una cosilla.

**Comment by alu0100836059** [comment]
A mi también me salieron solo que después los borré. Supongo que aquí se podrá hacer lo mismo dejando solamente lo necesario para que rule.

**Comment by alu0100836059** [comment]
Ya funciona, tenemos que revisar unas cuantas cosas porque ahora me doy cuenta que falta mucho por cubrir con las pruebas del spec.js. Pero bien, así creo que es más fácil saber que nos falta y que no :)
